### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by tong1101** [AceCoooool/LEDNet#1]
AssertionError: Traceback (most recent call last):
  File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ydc/tl/pytorch/LEDNet-master/data/cityscapes.py", line 93, in __getitem__
    img, mask = self._sync_transform(img, mask)
  File "/home/ydc/tl/pytorch/LEDNet-master/data/base_seg.py", line 80, in _sync_transform
    img, mask = self._img_transform(img), self._mask_transform(mask)
  File "/home/ydc/tl/pytorch/LEDNet-master/data/cityscapes.py", line 105, in _mask_transform
    target = self._class_to_index(np.array(mask).astype('int64'))
  File "/home/ydc/tl/pytorch/LEDNet-master/data/cityscapes.py", line 79, in _class_to_index
    assert (value in self._mapping)
AssertionError

How to solve it?

**Comment by tong1101** [comment]
I solved the problem above and then the problem followed is:
................
cannot find the mask or image: ./citys/leftImg8bit/train/hanover_000000_014537.png ./citys/gtFine/train/train/hanover_000000_014537.png
cannot find the mask or image: ./citys/leftImg8bit/train/ulm_000080_000019.png ./citys/gtFine/train/train/ulm_000080_000019.png
cannot find the mask or image: ./citys/leftImg8bit/train/zurich_000005_000019.png ./citys/gtFine/train/train/zurich_000005_000019.png
cannot find the mask or image: ./citys/leftImg8bit/train/stuttgart_000039_000019.png ./citys/gtFine/train/train/stuttgart_000039_000019.png
cannot find the mask or image: ./citys/leftImg8bit/train/erfurt_000098_000019.png ./citys/gtFine/train/train/erfurt_000098_000019.png
cannot find the mask or image: ./citys/leftImg8bit/train/aachen_000095_000019.png ./citys/gtFine/train/train/aachen_000095_000019.png
cannot find the mask or image: ./citys/leftImg8bit/train/strasbourg_000001_022836.png ./citys/gtFine/train/train/strasbourg_000001_022836.png
cannot find the mask or image: ./citys/leftImg8bit/train/strasbourg_000001_029696.png ./citys/gtFine/train/train/strasbourg_000001_029696.png
cannot find the mask or image: ./citys/leftImg8bit/train/hanover_000000_030546.png ./citys/gtFine/train/train/hanover_000000_030546.png
cannot find the mask or image: ./citys/leftImg8bit/train/krefeld_000000_023510.png ./citys/gtFine/train/train/krefeld_000000_023510.png
cannot find the mask or image: ./citys/leftImg8bit/train/hamburg_000000_099368.png ./citys/gtFine/train/train/hamburg_000000_099368.png
cannot find the mask or image: ./citys/leftImg8bit/train/hamburg_000000_080438.png ./citys/gtFine/train/train/hamburg_000000_080438.png
Found 0 images in the folder ./citys/leftImg8bit/train
Traceback (most recent call last):

  File "<ipython-input-33-466877d0b988>", line 1, in <module>
    runfile('/home/ydc/tl/pytorch/LEDNet-master/train.py', wdir='/home/ydc/tl/pytorch/LEDNet-master')

  File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/ydc/tl/pytorch/LEDNet-master/train.py", line 268, in <module>
    trainer = Trainer(args)

  File "/home/ydc/tl/pytorch/LEDNet-master/train.py", line 101, in __init__
    args.dataset, split=args.train_split, mode='train', **data_kwargs)

  File "/home/ydc/tl/pytorch/LEDNet-master/data/__init__.py", line 10, in get_segmentation_dataset
    return datasets[name.lower()](**kwargs)

  File "/home/ydc/tl/pytorch/LEDNet-master/data/cityscapes.py", line 64, in __init__
    " + self.root + "\n")

RuntimeError: Found 0 images in subfolders of:                 ./citys/

How to solve it?

**Comment by AceCoooool** [comment]
1. https://github.com/AceCoooool/LEDNet/blob/322fbd7ce08fd1dd50c2a226a4e05d4590001588/data/cityscapes.py#L54 you can change the root to your dataset folder

2. run the https://github.com/AceCoooool/LEDNet/blob/322fbd7ce08fd1dd50c2a226a4e05d4590001588/data/cityscapes.py#L111 to debug where is the bug.

**Comment by AceCoooool** [comment]
The default root of my dataset is :
```
--citys
   --leftImg8bit
      --train
         --aachen
           --xxx.png
           --...
         --bochum
         --...
      --val
         --...
   --gtFine
      --train
         --aachen
         --bochum
         --...
```

**Comment by tong1101** [comment]
Traceback (most recent call last):
  File "<ipython-input-21-466877d0b988>", line 1, in <module>
    runfile('/home/ydc/tl/pytorch/LEDNet-master/train.py', wdir='/home/ydc/tl/pytorch/LEDNet-master')

  File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/ydc/tl/pytorch/LEDNet-master/train.py", line 270, in <module>
    trainer.training()

  File "/home/ydc/tl/pytorch/LEDNet-master/train.py", line 171, in training
    outputs = self.net(image)

  File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/ydc/tl/pytorch/LEDNet-master/model/lednet.py", line 23, in forward
    x = self.encoder(x)

  File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)

  File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/ydc/tl/pytorch/LEDNet-master/model/basic.py", line 38, in forward
    return torch.cat([x1, x2], dim=1)

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 67 and 68 in dimension 2 at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/THC/generic/THCTensorMath.cu:87

**Comment by AceCoooool** [comment]
Thank you for point this out, just fix it by (I will update code soon)
https://github.com/AceCoooool/LEDNet/blob/322fbd7ce08fd1dd50c2a226a4e05d4590001588/model/basic.py#L33
to `self.pool = nn.MaxPool2d(2, ceil_mode=True)`

**Comment by tong1101** [comment]
Thanks for your help.I run the code successfully
Can you reproduce the performance？

**Comment by AceCoooool** [comment]
I will try two experiments:
1. add more epochs to see the performance (without pretrained model from imagenet, fast-SCNN using 1000 epochs.)
2. use large size to train (the paper may use 1024x512? I am not sure)

**Comment by tong1101** [comment]
0%|          | 0/500 [00:00<?, ?it/s]Traceback (most recent call last):

  File "<ipython-input-1-466877d0b988>", line 1, in <module>
    runfile('/home/ydc/tl/pytorch/LEDNet-master/train.py', wdir='/home/ydc/tl/pytorch/LEDNet-master')

  File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/ydc/tl/pytorch/LEDNet-master/train.py", line 270, in <module>
    trainer.training()

  File "/home/ydc/tl/pytorch/LEDNet-master/train.py", line 213, in training
    metrics = self.validate()

  File "/home/ydc/tl/pytorch/LEDNet-master/train.py", line 234, in validate
    self.metric.update(target, outputs)

  File "/home/ydc/tl/pytorch/LEDNet-master/utils/metric_seg.py", line 41, in update
    evaluate_worker(self, labels, preds)

  File "/home/ydc/tl/pytorch/LEDNet-master/utils/metric_seg.py", line 31, in evaluate_worker
    inter, union = batch_intersection_union(pred, label, self.nclass)

  File "/home/ydc/tl/pytorch/LEDNet-master/utils/metric_seg.py", line 122, in batch_intersection_union
    area_inter = torch.histc(intersection, bins=nbins, min=mini, max=maxi)

RuntimeError: histc is not implemented for type torch.cuda.FloatTensor

**Comment by AceCoooool** [comment]
please check your pytorch version.
